import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f5f5f5',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#f5f5f5',
    },
    loadingText: {
      marginTop: 16,
      color: '#777',
      fontSize: 16,
    },
    errorContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#f5f5f5',
      padding: 20,
    },
    errorText: {
      fontSize: 18,
      color: '#555',
      marginTop: 16,
      marginBottom: 24,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 60,
      paddingBottom: 16,
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    backButton: {
      padding: 8,
    },
    backButtonText: {
      color: '#0096FF',
      fontSize: 16,
      fontWeight: '600',
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: '#333',
      marginLeft: 8,
    },
    trackingInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#fff',
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    trackingNumber: {
      fontSize: 18,
      fontWeight: '700',
      color: '#333',
    },
    statusBadge: {
      backgroundColor: '#e0f7fa',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
    },
    statusBadgeText: {
      color: '#0277bd',
      fontSize: 14,
      fontWeight: '600',
    },
    card: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      margin: 16,
      marginBottom: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: '#333',
      marginBottom: 16,
    },
    statusBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
    },
    statusStep: {
      alignItems: 'center',
      flex: 1,
    },
    statusDot: {
      width: 16,
      height: 16,
      borderRadius: 8,
      marginBottom: 8,
    },
    statusLine: {
      height: 2,
      flex: 1,
      position: 'absolute',
      top: 8,
      right: 0,
      left: 16,
      zIndex: -1,
    },
    statusActive: {
      backgroundColor: '#0096FF',
    },
    statusInactive: {
      backgroundColor: '#e0e0e0',
    },
    statusLabel: {
      fontSize: 12,
      fontWeight: '500',
      textAlign: 'center',
    },
    statusTextActive: {
      color: '#0096FF',
    },
    statusTextInactive: {
      color: '#999',
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    infoItem: {
      flex: 1,
    },
    infoLabel: {
      fontSize: 14,
      color: '#777',
      marginBottom: 4,
    },
    infoValue: {
      fontSize: 16,
      color: '#333',
      fontWeight: '500',
    },
    paymentInfo: {
      marginTop: 8,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: '#f0f0f0',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    paymentLabel: {
      fontSize: 16,
      color: '#333',
      fontWeight: '600',
    },
    paymentValue: {
      fontSize: 18,
      color: '#2e7d32',
      fontWeight: '700',
    },
    updateItem: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    updateDot: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: '#0096FF',
      marginTop: 6,
      marginRight: 12,
    },
    updateLine: {
      width: 2,
      backgroundColor: '#e0e0e0',
      position: 'absolute',
      top: 18,
      bottom: -8,
      left: 5,
    },
    updateContent: {
      flex: 1,
    },
    updateStatus: {
      fontSize: 16,
      fontWeight: '600',
      color: '#333',
    },
    updateLocation: {
      fontSize: 14,
      color: '#555',
      marginTop: 2,
    },
    updateNote: {
      fontSize: 14,
      color: '#777',
      marginTop: 4,
      fontStyle: 'italic',
    },
    updateTime: {
      fontSize: 12,
      color: '#999',
      marginTop: 4,
    },
    actionsCard: {
      backgroundColor: '#fff',
      borderRadius: 12,
      padding: 16,
      margin: 16,
      marginBottom: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    actionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#f0f0f0',
    },
    actionButtonText: {
      fontSize: 16,
      marginLeft: 12,
      color: '#333',
      fontWeight: '500',
    },
  });

  export default styles;